### ISSUE TITLE
Color streams are empty

### ISSUE THREAD

**Issue by floe** [orbbec/astra#13]
Just received my Astra Pro S, built the SDK and tried the examples (on Ubuntu 16.04 x64, Kernel 4.4.0).

However, all examples that somehow access the color stream (`SimpleColorViewer-SFML, SimpleStreamViewer-SFML, MultiSensorViewer-SFML`) only show a black window.

Those that only use the depth stream (e.g. `SimpleDepthViewer-SFML, SimpleHandViewer-SFML`) work fine; when I use some generic camera application such as `cheese`, I can also view the color stream separately. udev rules seem to be installed correctly, same problem also occurs when running the samples as root.

Any ideas what the reason could be?

**Comment by JoshBlake** [comment]
Astra Pro includes a UVC color camera, so accessing color camera requires using a UVC API or wrapper such as within OpenCV. The SDK currently uses the OpenNI 2 driver layer as a backend, so is limited at the moment by lack of UVC support in the OpenNI 2 layer. The reason some of the samples only show a black window is because the simple ones start both depth and color on a single StreamSet, which provides synchronized frames. Since the driver isn't delivering color frames, the StreamSet keeps waiting. A solution would be to use a StreamSet for depth and separate StreamSet for color, but then with Astra one would not receive synchronized frames. Hope that helps!

**Comment by floe** [comment]
Hm, ok. I'm fine with unsynchronized frames for the moment; what I would still need, however, is depth <-> color registration. Is that functionality possible in this scenario?

**Comment by JoshBlake** [comment]
Registered depth is a hardware mode that you can enable on the depth stream. 
````
depthStream.enable_registration(true);
````
This should work regardless of the color stream.

**Comment by floe** [comment]
Just for my understanding: if I enable registration, then I will get depth pixels projected into the colour camera space, correct?

**Comment by JoshBlake** [comment]
Yes, that's correct. FYI, you may be able to find some additional information from other users on https://3dclub.orbbec3d.com if you search for registration.

**Comment by floe** [comment]
Thanks!

**Comment by floe** [comment]
After reading the forums for a bit, it looks like there are a couple of undocumented issues (different crop when using HD stream for the color camera, horizontal shift of 19 or 20 pixels between color and depth). Is there any improved documentation or code available?
